local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', builtin.live_grep, {})
vim.keymap.set('n', '<leader>pr', function()
  builtin.lsp_references({ jump_type = "vsplit" })
end)
vim.keymap.set('n', '<leader>pd', function()
  builtin.lsp_definitions({ jump_type = "vsplit" })
end)
